services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_USER: ${POSTGRES_USER:-moonshot}
      POSTGRES_DB: ${POSTGRES_DB:-moonshot}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '9080:8080'

  php:
    image: php:8.2-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: >
      sh -c "apt-get update &&
        apt-get install -y libpq-dev &&
        docker-php-ext-install pdo pdo_pgsql &&
        php -S 0.0.0.0:8000 -t public"
    depends_on:
      - database

volumes:
  postgres_data:
