/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qdLixCeLQuz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Loader() {
  return (
    (<div className="flex items-center justify-center h-screen">
      <div
        className="w-16 h-16 border-4 rounded-full animate-spin border-primary border-t-transparent" />
    </div>)
  );
}
